DROP TABLE VENTAP_RODUCTO IF EXISTS;
DROP TABLE VENTA IF EXISTS;
DROP TABLE DOMICILIO IF EXISTS;
DROP TABLE CLIENTE IF EXISTS;
DROP TABLE PRODUCTO IF EXISTS;

CREATE TABLE CLIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DNI BIGINT NOT NULL UNIQUE,
    ISACTIVO BOOLEAN NOT NULL,
    REPUTACION INT NOT NULL
);

CREATE TABLE PRODUCTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRECIO DECIMAL(10, 2),
    NOMBRE VARCHAR(150),
    STOCK INT
);

CREATE TABLE DOMICILIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CALLE VARCHAR(100) NOT NULL,
    ALTURA INT NOT NULL,
    PISO INT,
    DEPARTAMENTO VARCHAR(50),
    CP VARCHAR(20) NOT NULL,
    LOCALIDAD VARCHAR(100) NOT NULL,
    PROVINCIA VARCHAR(100) NOT NULL,
    CLIENTE INT,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE VENTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    CLIENTE INT,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE VENTA_PRODUCTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VENTA INT,
    PRODUCTO INT,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (VENTA) REFERENCES VENTA(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE
);
